[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Products"
  pageRef = "/blog/"
  weight = 20

[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 30

[[social]]
  name = "Facebook"
  pre = "fab facebook"
  url = "https://facebook.com/sepicelanka"
  weight = 30

[[social]]
  name = "WhatsApp"
  pre = "fab whatsapp"
  url = "https://wa.me/message/WMM6S3FQUT3PB1"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation